POST http://localhost:3000/api/auth/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0OGVkN2I5OGJhMjI5YzVlNzBhYmYyYyIsImZ1bGxOYW1lIjoiMTIzNDU2NzMiLCJ1c2VybmFtZSI6ImFiY2RlZiIsImVtYWlsIjoiMTIzQGdhbWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA4JEFWc3Z6NEFsQlYxc3RpREU5aEk5VHVUM25ia2F4WXZqYmNJTjlBeEcyV3JJZVR6MlJOZElLIiwiY29tZmlybVBhc3N3b3JkIjoiJDJhJDA4JG1iMXhGV0Z0LjJXNG5hNS9vNGtLTmV6dFBFak1UNHRLc0F2VzV4UTJQSi4yNlhIZkJwMy5LIiwiX192IjowfSwiaWF0IjoxNjg3MDkyNTIzfQ.CF0nr6zBSIZTK4abGGRvSyRFiMMcqI7ducTwYm3Uh3w

{
    "username": "abcdefg",
    "password": "1234567"
}

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhlYjI1ODFhYWRmNWJmNTc0YWViZGQiLCJpYXQiOjE2ODcwODEzODd9.lOLSflJsC7zJUQ_xOmnqiw8-keMVmYEZAZYEbzczV3I

{
    "fullName": "12345673",
    "username": "abcdefghk",
    "email": "123@gamil.com",
    "password": "1234567",
    "comfirmPassword": "1234567"
}

###

GET http://localhost:3000/api/todos/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0OGVkN2I5OGJhMjI5YzVlNzBhYmYyYyIsImZ1bGxOYW1lIjoiMTIzNDU2NzMiLCJ1c2VybmFtZSI6ImFiY2RlZiIsImVtYWlsIjoiMTIzQGdhbWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA4JEFWc3Z6NEFsQlYxc3RpREU5aEk5VHVUM25ia2F4WXZqYmNJTjlBeEcyV3JJZVR6MlJOZElLIiwiY29tZmlybVBhc3N3b3JkIjoiJDJhJDA4JG1iMXhGV0Z0LjJXNG5hNS9vNGtLTmV6dFBFak1UNHRLc0F2VzV4UTJQSi4yNlhIZkJwMy5LIiwiX192IjowfSwiaWF0IjoxNjg3MDkyNTIzfQ.CF0nr6zBSIZTK4abGGRvSyRFiMMcqI7ducTwYm3Uh3w

###
POST http://localhost:3000/api/todos/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0OGVkN2I5OGJhMjI5YzVlNzBhYmYyYyIsImZ1bGxOYW1lIjoiMTIzNDU2NzMiLCJ1c2VybmFtZSI6ImFiY2RlZiIsImVtYWlsIjoiMTIzQGdhbWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA4JEFWc3Z6NEFsQlYxc3RpREU5aEk5VHVUM25ia2F4WXZqYmNJTjlBeEcyV3JJZVR6MlJOZElLIiwiY29tZmlybVBhc3N3b3JkIjoiJDJhJDA4JG1iMXhGV0Z0LjJXNG5hNS9vNGtLTmV6dFBFak1UNHRLc0F2VzV4UTJQSi4yNlhIZkJwMy5LIiwiX192IjowfSwiaWF0IjoxNjg3MDkyNTIzfQ.CF0nr6zBSIZTK4abGGRvSyRFiMMcqI7ducTwYm3Uh3w

{
    "name": "post 122",
    "status": "okk"
}

###

PUT http://localhost:3000/api/todos/edit/648f041b60e6d6b2f4f52ac9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0OGVkN2I5OGJhMjI5YzVlNzBhYmYyYyIsImZ1bGxOYW1lIjoiMTIzNDU2NzMiLCJ1c2VybmFtZSI6ImFiY2RlZiIsImVtYWlsIjoiMTIzQGdhbWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA4JEFWc3Z6NEFsQlYxc3RpREU5aEk5VHVUM25ia2F4WXZqYmNJTjlBeEcyV3JJZVR6MlJOZElLIiwiY29tZmlybVBhc3N3b3JkIjoiJDJhJDA4JG1iMXhGV0Z0LjJXNG5hNS9vNGtLTmV6dFBFak1UNHRLc0F2VzV4UTJQSi4yNlhIZkJwMy5LIiwiX192IjowfSwiaWF0IjoxNjg3MDk0MTI4fQ.-nxNx-vav_EkCnnEL5NbWHktxk1bQeMdlPMkjWoOf_M

{
    "name": "post 122345",
    "status": "okk"
}

###

DELETE http://localhost:3000/api/todos/delete/648f041b60e6d6b2f4f52ac9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0OGVkN2I5OGJhMjI5YzVlNzBhYmYyYyIsImZ1bGxOYW1lIjoiMTIzNDU2NzMiLCJ1c2VybmFtZSI6ImFiY2RlZiIsImVtYWlsIjoiMTIzQGdhbWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA4JEFWc3Z6NEFsQlYxc3RpREU5aEk5VHVUM25ia2F4WXZqYmNJTjlBeEcyV3JJZVR6MlJOZElLIiwiY29tZmlybVBhc3N3b3JkIjoiJDJhJDA4JG1iMXhGV0Z0LjJXNG5hNS9vNGtLTmV6dFBFak1UNHRLc0F2VzV4UTJQSi4yNlhIZkJwMy5LIiwiX192IjowfSwiaWF0IjoxNjg3MDk0MTI4fQ.-nxNx-vav_EkCnnEL5NbWHktxk1bQeMdlPMkjWoOf_M


###

POST http://localhost:3000/api/todos/search/?name=post 12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0OGVkN2I5OGJhMjI5YzVlNzBhYmYyYyIsImZ1bGxOYW1lIjoiMTIzNDU2NzMiLCJ1c2VybmFtZSI6ImFiY2RlZiIsImVtYWlsIjoiMTIzQGdhbWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA4JEFWc3Z6NEFsQlYxc3RpREU5aEk5VHVUM25ia2F4WXZqYmNJTjlBeEcyV3JJZVR6MlJOZElLIiwiY29tZmlybVBhc3N3b3JkIjoiJDJhJDA4JG1iMXhGV0Z0LjJXNG5hNS9vNGtLTmV6dFBFak1UNHRLc0F2VzV4UTJQSi4yNlhIZkJwMy5LIiwiX192IjowfSwiaWF0IjoxNjg3MDk0MTI4fQ.-nxNx-vav_EkCnnEL5NbWHktxk1bQeMdlPMkjWoOf_M

