POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "huyentrang",
    "password": "1234567"
}

###

GET http://localhost:3000/api/todos/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0OTI4NjdjMGIwN2M4ZDQ5YzIwY2I0MyIsImZ1bGxOYW1lIjoiaHV5IiwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiaHV5MjAyMjIwMDNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMDgkSHA0Vy9Yd0xhVTVYN3RqTktVY25zdS9TeU5td2FOQ2pVbFZLZ3N6R0x4YjE1c01pV0U1blMiLCJjb21maXJtUGFzc3dvcmQiOiIkMmEkMDgkcWRyRXRUd0NzR2d1RWdJMnMvTFRFT2VVQTZJdFlhbXNhVUdVOW5BMUxXSjk5djlnQTBNU2EiLCJpbWFnZSI6IiIsIl9fdiI6MH0sImlhdCI6MTY4NzQ5OTg4NywiZXhwIjoxNjg3NTg2Mjg3fQ.HvfwwVDRqXke_u1yycDG8UKQlqgiQyluYCbZBiqGURA


###

PUT http://localhost:3000/api/todos/edit/648f041b60e6d6b2f4f52ac9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImltYWdlIjoiaHR0cHM6Ly9hbnRpbWF0dGVyLnZuL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDIyLzExL2FuaC1hdmF0YXItdHJhbmctZmItbWFjLWRpbmguanBnIiwiX2lkIjoiNjQ4ZWQ3Yjk4YmEyMjljNWU3MGFiZjJjIiwiZnVsbE5hbWUiOiIxMjM0NTY3MyIsInVzZXJuYW1lIjoiYWJjZGVmIiwiZW1haWwiOiIxMjNAZ2FtaWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMDgkQVZzdno0QWxCVjFzdGlERTloSTlUdVQzbmJrYXhZdmpiY0lOOUF4RzJXckllVHoyUk5kSUsiLCJjb21maXJtUGFzc3dvcmQiOiIkMmEkMDgkbWIxeEZXRnQuMlc0bmE1L280a0tOZXp0UEVqTVQ0dEtzQXZXNXhRMlBKLjI2WEhmQnAzLksiLCJfX3YiOjB9LCJpYXQiOjE2ODc1MTcwNDN9.akcsOl1Ipx4CRK7HD8174J1dau4DJ99DW5T6isOngVc

{
    "name": "huy",
    "description": "huy",
    "label": "huy"
}

###
POST http://localhost:3000/api/todos/search/?name=Nguyen Quang Huy1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0OTI4YmU3NzUwZjRjMWZkMWE4ZmY4NyIsImZ1bGxOYW1lIjoiaHV5ZW50cmFuZyIsInVzZXJuYW1lIjoiaHV5ZW50cmFuZyIsImVtYWlsIjoiaHV5ZW50cmFuZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCRjdWxEWVU0ZENOV3kzcm85bTFBTjZ1MThwa0szUzJIUTBaazZrMHlWMHZpUzFGREhhLzdhLiIsImNvbWZpcm1QYXNzd29yZCI6IiQyYSQwOCRQcXJwY01NV2FCZVFpTlV2NklBcmEud3RrdXRabmpkdnZNaHNvMzhTMGNyMFkuU3p1NUxnLiIsImltYWdlIjoiIiwiX192IjowfSwiaWF0IjoxNjg3NzUzNDc4fQ.X6AYPOESe7GwsvqiRMK93g_9EBAs8AWtcxJb0ye4A7k
