POST http://localhost:3000/api/user/encode-desc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE1NTkzNDI1NjhhYTBjNGZhZTdlZjUiLCJpYXQiOjE2OTE4MjI2NjMsImV4cCI6MTY5MTgyMzU2M30.2kBziRq7JKVYKmpN-5nhR1cPY608Ie_fVTvkuB7nroA

{
    "description": "abc",
    "isChecked": true
}
###

GET http://localhost:3000/api/user/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGRjZGViNzliMjE2MDg2NWY1MWYyYmEiLCJpYXQiOjE2OTIxOTc0NzQsImV4cCI6MTY5MjE5ODM3NH0.XyHAV6ese71Renw-6mWRGpxQ1XeZTy4U4nfcJvACoJk
###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "admin1",
    "password": "1234567"
}

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "fullName": "Huy",
    "username": "admin1",
    "email": "huy2",
    "password": "1234567"
}

###

PUT http://localhost:3000/api/auth/update-role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGRjZGViNzliMjE2MDg2NWY1MWYyYmEiLCJpYXQiOjE2OTIxOTc0NzQsImV4cCI6MTY5MjE5ODM3NH0.XyHAV6ese71Renw-6mWRGpxQ1XeZTy4U4nfcJvACoJk

{
    "name": "user"
}